language: node_js
node_js:
 - "12.17.0"
script:
 - npm run lint
 - npm run test:lib
before_deploy:
 - npm run build
 - cd dist/ngx-interactive-paycard-lib
deploy:
   provider: npm
   email: "$NPM_EMAIL"
   api:key: "NPM_API_TOKEN"
   skip_cleanup: true
   on:
    tags: true